p8105_hw1_zx2424
================

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

## Problem 1

``` r
data("penguins", package = "palmerpenguins")
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

Dataset “penguins” includes three species –“Adelie”, “Chinstrap” and
“Gentoo”, three islands –“Biscoe”, “Dream” and “Torgersen”,
bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g,
sex–“female” and “male”, and year. The “penguins” dataset includes 344
rows and 8 columns. The mean flipper length is 200.9.

``` r
plot_fb = tibble(
  x = pull(penguins, bill_length_mm),
  y = pull(penguins, flipper_length_mm)
)
sp = pull(penguins, species)
ggplot(plot_fb, aes(x = x, y = y, color = sp)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_zx2424_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

``` r
ggsave("first_scatterplot.pdf")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values (geom_point).

The plot above is a scatterplot of flipper_length_mm (y) vs
bill_length_mm (x). The red points represent Adelle penguins, the green
ones represent Chinstrap penguins, while the blue ones represents Gentoo
penguins. And the scatterplot is exported to the project directory and
named “first_scatterplot.pdf”.

## Problem 2

Create a data frame.

``` r
dataframe = tibble(
  vec_numeric = rnorm(10, sd = 1),
  vec_logical = vec_numeric > 0,
  vec_char = c("A","B", "C", "D", "E", "F", "G", "H", "I", "J"),
  vec_factor = factor(c("Low", "Middle", "High", "Low", "Middle", "High", "Low", "Middle", "High","High"))
)
```

Try to take mean of each variable in the dataframe.

``` r
mean(pull(dataframe, vec_numeric))
```

    ## [1] 0.2277393

``` r
mean(pull(dataframe, vec_logical))
```

    ## [1] 0.6

``` r
mean(pull(dataframe, vec_char))
```

    ## Warning in mean.default(pull(dataframe, vec_char)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(dataframe, vec_factor))
```

    ## Warning in mean.default(pull(dataframe, vec_factor)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

From the results of the above code, we can discover that taking the mean
of numeric variables and logical variables works. And we are not able to
take the mean of character variables and factor variables.

``` r
as.numeric(pull(dataframe, vec_logical))
as.numeric(pull(dataframe, vec_char))
as.numeric(pull(dataframe, vec_factor))
```

Logical variables and factor variables can be converted to numeric
variables, while the character variables cannot. Because for logical
variables, “1” represents “TRUE”, and “0” represents “FALSE”.
Consequently, its mean be calculated. And for factor vector, each
different factor “level” can be converted a number. But before being
converted to actual number, factor “levels” are not taken as numbers, so
its mean cannot be calculated. Character variables cannot be represented
by any number, contributing to the result “NA” when taking its mean.
